name: WhiteSource Scan
description: Used for performing WhiteSource scanning.

inputs:
  whitesource_excludes:
    description: "Files to exclude from WhiteSource Scan"
    required: false
    default: ""
  target_directory:
    description: "Directory that contains the JAR files"
    required: true
    default: "."
  language:
    description: "Language to run WhiteSource Scan against"
    required: true
    default: ""
  whitesource_api_key:
    description: "API Key for WhiteSource"
    required: true
    default: ""
  whitesource_project_key:
    description: "Project key for WhiteSource"
    required: false
    default: ""
  whitesource_product_name:
    description: "Product Name for WhiteSource"
    required: false
    default: "maas"
  whitesource_product_version:
    description: "Product Version for WhiteSource"
    required: false
    default: ""
  whitesource_project_name:
    description: "Project Name for WhiteSource"
    required: false
    default: ""
  whitesource_project_version:
    description: "Project Version for WhiteSource"
    required: false
    default: ""
  whitesource_config_file:
    description: "Configuration file for WhiteSource"
    required: false
    default: ""
  whitesource_project_state_checker:
    description: "Poll Mend/Whitesource to be update completed after a scan"
    required: false
    default: "true"
  github_token:
    description: "GitHub token used for pulling the container image"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: No_Op whitesource
      shell: 
      run: echo "Whitesource is deprecated"