name: Fossa Guard
description: Run Fossa Guard scripts packaged in the maas-build-actions Docker container.
inputs:
  fossa_api_key:
    description: "FOSSA API key"
    required: true
  fossa_project_id:
    description: "FOSSA project ID"
    required: true
  fossa_category:
    description: "Issue category, licensing or vulnerability"
    required: true
  fossa_mode:
    description: "Comma-separated list of actions: BLOCK, REPORT, or both (e.g. BLOCK,REPORT)"
    required: false
  block_on:
    description: "Comma-separated list of issue types to block on. For licensing: policy_conflict,policy_flag. For vulnerability: critical,high,medium,low."
    required: false
  fossa_branch:
    description: "Specify a branch name to query issues for that branch (e.g., 'main', 'develop', 'feature/xyz')"
    required: false
  fossa_revision:
    description: "Specify a commit SHA to filter issues for a specific revision"
    required: false
  fossa_revision_scan_id:
    description: "Specify a revision scan ID for more granular filtering (advanced usage)"
    required: false
  fossa_release:
    description: "Specify a release group ID to filter issues for a release group (advanced usage)"
    required: false
  fossa_release_scan_id:
    description: "Specify a release scan ID for release group filtering (advanced usage)"
    required: false
  slack_token:
    description: "Slack bot token for posting messages (optional)"
    required: false
  slack_channel:
    description: "Slack channel ID to post to (optional)"
    required: false
  slack_thread_ts:
    description: "Slack thread timestamp to reply to an existing thread (optional)"
    required: false
  github_repository:
    description: "GitHub repository name for links (optional)"
    required: false
  github_run_id:
    description: "GitHub Actions run ID for build links (optional)"
    required: false
  github_server_url:
    description: "GitHub server URL (default: https://github.com) (optional)"
    required: false
  github_token:
    description: "GitHub token for PR comments and status checks"
    required: false
    default: ${{ github.token }}
  enable_pr_comment:
    description: "Enable PR commenting (true/false)"
    required: false
    default: "false"
  enable_status_check:
    description: "Enable GitHub status checks (true/false)"
    required: false
    default: "false"
  status_check_name:
    description: "Custom name for GitHub status check"
    required: false
    default: "FOSSA Guard"
  pr_comment_max_violations:
    description: "Maximum violations to show in PR comment"
    required: false
    default: "5"
  enable_diff_mode:
    description: "Enable diff mode to show only new issues (true/false)"
    required: false
    default: "false"
  diff_base_revision_sha:
    description: "Base revision SHA to compare against (optional - auto-detects default branch)"
    required: false
  enable_license_enrichment:
    description: "Show declared/discovered license indicators (true/false)"
    required: false
    default: "true"

runs:
  using: docker
  image: docker://ghcr.io/solacedev/maas-build-actions:DATAGO-123543
  entrypoint: /bin/sh
  args:
    - -c
    - |
      export FOSSA_API_KEY="$INPUT_FOSSA_API_KEY"
      export FOSSA_PROJECT_ID="$INPUT_FOSSA_PROJECT_ID"
      export FOSSA_CATEGORY="$INPUT_FOSSA_CATEGORY"
      if [ -n "$INPUT_FOSSA_MODE" ]; then export FOSSA_MODE="$INPUT_FOSSA_MODE"; fi
      if [ -n "$INPUT_BLOCK_ON" ]; then export BLOCK_ON="$INPUT_BLOCK_ON"; fi
      if [ -n "$INPUT_FOSSA_BRANCH" ]; then export FOSSA_BRANCH="$INPUT_FOSSA_BRANCH"; fi
      if [ -n "$INPUT_FOSSA_REVISION" ]; then export FOSSA_REVISION="$INPUT_FOSSA_REVISION"; fi
      if [ -n "$INPUT_FOSSA_REVISION_SCAN_ID" ]; then export FOSSA_REVISION_SCAN_ID="$INPUT_FOSSA_REVISION_SCAN_ID"; fi
      if [ -n "$INPUT_FOSSA_RELEASE" ]; then export FOSSA_RELEASE="$INPUT_FOSSA_RELEASE"; fi
      if [ -n "$INPUT_FOSSA_RELEASE_SCAN_ID" ]; then export FOSSA_RELEASE_SCAN_ID="$INPUT_FOSSA_RELEASE_SCAN_ID"; fi
      if [ -n "$INPUT_SLACK_TOKEN" ]; then export SLACK_TOKEN="$INPUT_SLACK_TOKEN"; fi
      if [ -n "$INPUT_SLACK_CHANNEL" ]; then export SLACK_CHANNEL="$INPUT_SLACK_CHANNEL"; fi
      if [ -n "$INPUT_SLACK_THREAD_TS" ]; then export SLACK_THREAD_TS="$INPUT_SLACK_THREAD_TS"; fi
      if [ -n "$INPUT_GITHUB_REPOSITORY" ]; then export GITHUB_REPOSITORY="$INPUT_GITHUB_REPOSITORY"; fi
      if [ -n "$INPUT_GITHUB_RUN_ID" ]; then export GITHUB_RUN_ID="$INPUT_GITHUB_RUN_ID"; fi
      if [ -n "$INPUT_GITHUB_SERVER_URL" ]; then export GITHUB_SERVER_URL="$INPUT_GITHUB_SERVER_URL"; fi
      if [ -n "$INPUT_GITHUB_TOKEN" ]; then export GITHUB_TOKEN="$INPUT_GITHUB_TOKEN"; fi
      if [ -n "$INPUT_ENABLE_PR_COMMENT" ]; then export ENABLE_PR_COMMENT="$INPUT_ENABLE_PR_COMMENT"; fi
      if [ -n "$INPUT_ENABLE_STATUS_CHECK" ]; then export ENABLE_STATUS_CHECK="$INPUT_ENABLE_STATUS_CHECK"; fi
      if [ -n "$INPUT_STATUS_CHECK_NAME" ]; then export STATUS_CHECK_NAME="$INPUT_STATUS_CHECK_NAME"; fi
      if [ -n "$INPUT_PR_COMMENT_MAX_VIOLATIONS" ]; then export PR_COMMENT_MAX_VIOLATIONS="$INPUT_PR_COMMENT_MAX_VIOLATIONS"; fi
      if [ -n "$INPUT_ENABLE_DIFF_MODE" ]; then export ENABLE_DIFF_MODE="$INPUT_ENABLE_DIFF_MODE"; fi
      if [ -n "$INPUT_DIFF_BASE_REVISION_SHA" ]; then export DIFF_BASE_REVISION_SHA="$INPUT_DIFF_BASE_REVISION_SHA"; fi
      if [ -n "$INPUT_ENABLE_LICENSE_ENRICHMENT" ]; then export ENABLE_LICENSE_ENRICHMENT="$INPUT_ENABLE_LICENSE_ENRICHMENT"; fi
      echo "Debug: Inputs:"
      echo "FOSSA_API_KEY: [REDACTED]"
      echo "FOSSA_PROJECT_ID: $FOSSA_PROJECT_ID"
      echo "FOSSA_CATEGORY: $FOSSA_CATEGORY"
      echo "FOSSA_MODE: $FOSSA_MODE"
      echo "BLOCK_ON: $BLOCK_ON"
      echo "FOSSA_BRANCH: $FOSSA_BRANCH"
      echo "FOSSA_REVISION: $FOSSA_REVISION"
      echo "FOSSA_REVISION_SCAN_ID: $FOSSA_REVISION_SCAN_ID"
      echo "FOSSA_RELEASE: $FOSSA_RELEASE"
      echo "FOSSA_RELEASE_SCAN_ID: $FOSSA_RELEASE_SCAN_ID"
      echo "SLACK_TOKEN: [REDACTED]"
      echo "SLACK_CHANNEL: $SLACK_CHANNEL"
      echo "SLACK_THREAD_TS: $SLACK_THREAD_TS"
      echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
      echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
      echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
      echo "GITHUB_TOKEN: [REDACTED]"
      echo "ENABLE_PR_COMMENT: $ENABLE_PR_COMMENT"
      echo "ENABLE_STATUS_CHECK: $ENABLE_STATUS_CHECK"
      echo "STATUS_CHECK_NAME: $STATUS_CHECK_NAME"
      echo "PR_COMMENT_MAX_VIOLATIONS: $PR_COMMENT_MAX_VIOLATIONS"
      echo "ENABLE_DIFF_MODE: $ENABLE_DIFF_MODE"
      echo "DIFF_BASE_REVISION_SHA: $DIFF_BASE_REVISION_SHA"
      echo "ENABLE_LICENSE_ENRICHMENT: $ENABLE_LICENSE_ENRICHMENT"
      echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
      echo "GITHUB_REF: $GITHUB_REF"
      echo "GITHUB_SHA: $GITHUB_SHA"
      echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
      echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
      source /maas-build-actions/venv/bin/activate
      python3 /maas-build-actions/scripts/fossa-guard/fossa_guard.py
