name: "Prisma Container Scan"
description: "Wrapper for Prisma Cloud container scanning using CONTAINER_PRISMA_* env vars."

inputs: {}

outputs:
  scan_passed:
    description: "Whether the scan passed without blocking issues (true/false)"
    value: ${{ steps.prisma_scan.outputs.scan_passed }}
  vuln_critical:
    description: "Number of critical vulnerabilities found"
    value: ${{ steps.prisma_scan.outputs.vuln_critical }}
  vuln_high:
    description: "Number of high severity vulnerabilities found"
    value: ${{ steps.prisma_scan.outputs.vuln_high }}
  vuln_medium:
    description: "Number of medium severity vulnerabilities found"
    value: ${{ steps.prisma_scan.outputs.vuln_medium }}
  vuln_low:
    description: "Number of low severity vulnerabilities found"
    value: ${{ steps.prisma_scan.outputs.vuln_low }}

runs:
  using: "composite"
  steps:
    - name: Prisma Container - Testing Placeholder
      id: prisma_scan
      shell: bash
      run: |
        echo "::group::🧪 Prisma Container Scan - Testing"
        echo "This is a placeholder for Prisma Cloud container scanning"
        echo "The Prisma scan integration will be implemented later"
        echo "::endgroup::"

        # Set dummy outputs for testing
        echo "scan_passed=true" >> $GITHUB_OUTPUT
        echo "vuln_critical=0" >> $GITHUB_OUTPUT
        echo "vuln_high=0" >> $GITHUB_OUTPUT
        echo "vuln_medium=0" >> $GITHUB_OUTPUT
        echo "vuln_low=0" >> $GITHUB_OUTPUT
