name: "Prisma Container Scan"
description: "Wrapper for Prisma Cloud container scanning using CONTAINER_PRISMA_* env vars."

inputs: {}

outputs:
  scan_passed:
    description: "Whether the scan passed without blocking issues (true/false)"
    value: ${{ steps.prisma_scan.outputs.scan_passed }}
  vuln_critical:
    description: "Number of critical vulnerabilities found"
    value: ${{ steps.prisma_scan.outputs.vuln_critical }}
  vuln_high:
    description: "Number of high severity vulnerabilities found"
    value: ${{ steps.prisma_scan.outputs.vuln_high }}
  vuln_medium:
    description: "Number of medium severity vulnerabilities found"
    value: ${{ steps.prisma_scan.outputs.vuln_medium }}
  vuln_low:
    description: "Number of low severity vulnerabilities found"
    value: ${{ steps.prisma_scan.outputs.vuln_low }}

runs:
  using: "composite"
  steps:
    - name: Prisma Container - Validate Environment Variables
      shell: bash
      run: |
        echo "::group::⚙️ Prisma Container - Validation"

        # Check required variables
        if [ -z "$CONTAINER_PRISMA_IMAGE_REGISTRY" ]; then
          echo "❌ Error: CONTAINER_PRISMA_IMAGE_REGISTRY is required"
          exit 1
        fi

        if [ -z "$CONTAINER_PRISMA_IMAGE_TAG" ]; then
          echo "❌ Error: CONTAINER_PRISMA_IMAGE_TAG is required"
          exit 1
        fi

        if [ -z "$CONTAINER_PRISMA_PCC_CONSOLE_URL" ]; then
          echo "❌ Error: CONTAINER_PRISMA_PCC_CONSOLE_URL is required"
          exit 1
        fi

        if [ -z "$CONTAINER_PRISMA_PCC_USER" ]; then
          echo "❌ Error: CONTAINER_PRISMA_PCC_USER is required"
          exit 1
        fi

        if [ -z "$CONTAINER_PRISMA_PCC_PASS" ]; then
          echo "❌ Error: CONTAINER_PRISMA_PCC_PASS is required"
          exit 1
        fi

        # Set default for image_repo if not provided (will use GitHub repo name)
        if [ -z "$CONTAINER_PRISMA_IMAGE_REPO" ]; then
          echo "ℹ️  CONTAINER_PRISMA_IMAGE_REPO not set, will use GitHub repository name"
        fi

        # Set default for twistcli_publish if not provided
        if [ -z "$CONTAINER_PRISMA_TWISTCLI_PUBLISH" ]; then
          echo "CONTAINER_PRISMA_TWISTCLI_PUBLISH=true" >> "$GITHUB_ENV"
        fi

        echo "✓ Environment variables validated"
        echo "::endgroup::"

    - name: Prisma Container - Call Prisma Cloud Scan
      id: prisma_scan
      uses: SolaceDev/solace-public-workflows/prisma-cloud-scan@main
      with:
        image_registry: ${{ env.CONTAINER_PRISMA_IMAGE_REGISTRY }}
        image_repo: ${{ env.CONTAINER_PRISMA_IMAGE_REPO }}
        image_tag: ${{ env.CONTAINER_PRISMA_IMAGE_TAG }}
        pcc_console_url: ${{ env.CONTAINER_PRISMA_PCC_CONSOLE_URL }}
        pcc_user: ${{ env.CONTAINER_PRISMA_PCC_USER }}
        pcc_pass: ${{ env.CONTAINER_PRISMA_PCC_PASS }}
        twistcli_publish: ${{ env.CONTAINER_PRISMA_TWISTCLI_PUBLISH }}
