name: hatch-install-with-caching
description: Hatch install with support for caching using uv.
inputs:
  min-python-version:
    description: "Minimum Python version to support."
    default: "3.10"
  max-python-version:
    description: "Maximum Python version to support."
    default: "3.13"
  build:
    description: "Whether to run the build step."
    default: "true"
outputs:
  matrix-present:
    description: "Whether the test matrix is present."
    value: ${{ steps.test-matrix-present.outputs.matrix-present == 'true' }}
  hatch-python-path:
    description: "The path to the Python interpreter."
    value: ${{ steps.export-python-path.outputs.hatch_python_path }}
runs:
  using: composite
  steps:
    - name: Verify 'pyproject.toml' exists
      run: test -f pyproject.toml
      shell: bash

    - name: Test Matrix Present
      id: test-matrix-present
      shell: bash
      run: |
        # Verify if hatch specific test matrix is present in pyproject.toml
        MATRIX_PRESENT=$(awk -v min="${{ inputs.min-python-version }}" -v max="${{ inputs.max-python-version }}" '
            /\[tool\.hatch\.envs\.hatch-test\]/ { in_env=1; next }
            in_env && /installer = "pip"/ { has_pip_installer=1; in_env=0 }
            /\[\[tool\.hatch\.envs\.hatch-test\.matrix\]\]/ { in_matrix=1; next }
            in_matrix && /python = \[/ {
              if (index($0, min)) found_min=1
              if (index($0, max)) found_max=1
              in_matrix=0
            }
            END {
              if (!has_pip_installer || !found_min || !found_max) {
                print "false"
                exit 0
              }
              print "true"
              exit 0
            }
          ' pyproject.toml)
        echo "matrix-present=$MATRIX_PRESENT" >> $GITHUB_OUTPUT

    - name: Install Python Versions for Hatch Test Matrix
      id: setup-python
      if: steps.test-matrix-present.outputs.matrix-present == 'true'
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: |
          ${{ inputs.min-python-version }}
          ${{ inputs.max-python-version }}

    - name: Install Python Version from pyproject.toml
      id: setup-python-default
      if: steps.test-matrix-present.outputs.matrix-present == 'false'
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version-file: "pyproject.toml"

    - name: Export Python Path For Hatch
      shell: bash
      id: export-python-path
      run: |
        if [ "${{ steps.test-matrix-present.outputs.matrix-present }}" == "true" ]; then          
          PYTHON_PATH=${{ steps.setup-python.outputs.python-path }}
        elif [ "${{ steps.test-matrix-present.outputs.matrix-present }}" == "false" ]; then
          PYTHON_PATH=${{ steps.setup-python-default.outputs.python-path }}
        fi
        echo "HATCH_PYTHON_PATH=${PYTHON_PATH}" >> $GITHUB_ENV
        echo "hatch_python_path=${PYTHON_PATH}" >> $GITHUB_OUTPUT

    - name: Install uv
      uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5

    - name: Install Hatch
      shell: bash
      run: uv tool install hatch

    - name: Create Hatch Environment
      shell: bash
      run: hatch -v env create

    - name: Create Hatch Environment for Matrix Python Versions
      shell: bash
      if: steps.test-matrix-present.outputs.matrix-present == 'true'
      run: |
        hatch env create hatch-test.py${{ inputs.min-python-version }}
        hatch env create hatch-test.py${{ inputs.max-python-version }}

    - name: Install twine
      shell: bash
      run: uv tool install twine

    - name: Build Hatch Package
      shell: bash
      if: inputs.build == 'true'
      run: |
        hatch build
