name: "Fossa Scan"
description: "Runs a Fossa scan using FOSSA_API_KEY and SCA_FOSSA_* env vars."

inputs: {}
runs:
  using: "composite"
  steps:
    - name: Fossa - Preparation step
      shell: bash
      run: |
        echo "::group::⚙️ Fossa Preparation"
        echo "Installing FOSSA CLI..."
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

        # Use the parameter parser script for analyze command
        export FOSSA_PARAMS_CONFIG="${GITHUB_ACTION_PATH}/fossa-params.json"
        source "${GITHUB_ACTION_PATH}/parse-fossa-params.sh"

        # Build analyze args
        build_fossa_args "analyze"
        echo "SCA_FOSSA_ADDITIONAL_ARGS=${FOSSA_CLI_ARGS}" >> "$GITHUB_ENV"

        # Build test args
        build_fossa_args "test"
        echo "SCA_FOSSA_TEST_ARGS=${FOSSA_CLI_ARGS}" >> "$GITHUB_ENV"

        echo "::endgroup::"

    - name: Fossa - Scan
      shell: bash
      run: |
        echo "::group::🔍 Fossa Scan"
        FOSSA_CMD="fossa analyze"

        echo "Running: $FOSSA_CMD $SCA_FOSSA_ADDITIONAL_ARGS"
        $FOSSA_CMD $SCA_FOSSA_ADDITIONAL_ARGS
        echo "::endgroup::"

    - name: FOSSA - Scan Wait For Results
      continue-on-error: true
      shell: bash
      run: |
        echo "::group::⏳ Fossa Wait For Results"
        echo "Running: fossa test $SCA_FOSSA_TEST_ARGS"
        fossa test $SCA_FOSSA_TEST_ARGS
        echo "::endgroup::"
