name: Hatch Release Preparation
description: |
  Prepares a Python package release: version bump, commit, and build.
  Must be followed by PyPI publish step (directly in workflow) and hatch-release-post action.

  Prerequisites:
  - Repository must be checked out with fetch-depth: 0 and ssh-key for pushing
  - Hatch must be configured in pyproject.toml

inputs:
  version:
    description: "Version bump type (patch, minor, major)"
    required: true
  max-python-version:
    description: "Maximum Python version to support."
    default: "3.13"

outputs:
  new_version:
    description: "The new version that was released"
    value: ${{ steps.set_output.outputs.new_version }}
  commit_hash:
    description: "The commit hash for the version bump commit"
    value: ${{ steps.set_commit_hash.outputs.commit_hash }}
  current_version:
    description: "The version before bumping"
    value: ${{ steps.current_version.outputs.current_version }}
  skip_bump:
    description: "Whether version bump was skipped (1 if skipped, 0 if not)"
    value: ${{ steps.check_bump.outputs.skip_bump }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{ inputs.max-python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5

    - name: Install Hatch
      shell: bash
      run: uv tool install hatch

    - name: Create Hatch Environment
      shell: bash
      run: hatch -v env create

    - name: Get Current Version
      id: current_version
      shell: bash
      run: |
        CURRENT_VERSION=$(hatch version)
        echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
        echo "current_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

    - name: Check if last commit was a version bump commit
      id: check_bump
      shell: bash
      run: |
        LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "Last commit: $LAST_COMMIT_MSG"
        if echo "$LAST_COMMIT_MSG" | grep -q "\[ci skip\] Bump version to"; then
            echo "Previous commit was a version bump. Skipping version bump."
            echo "SKIP_BUMP=1" >> $GITHUB_ENV
            echo "skip_bump=1" >> $GITHUB_OUTPUT
        else
            echo "SKIP_BUMP=0" >> $GITHUB_ENV
            echo "skip_bump=0" >> $GITHUB_OUTPUT
        fi

    - name: Bump Version
      id: bump_version
      shell: bash
      run: |
        if [ "$SKIP_BUMP" = "1" ]; then
            echo "Skipping version bump as the last commit was a version bump."
            echo "NEW_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
        else
            hatch version "${{ inputs.version }}"
            NEW_VERSION=$(hatch version)
            echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
        fi

    - name: Fail if the current version doesn't exist
      if: env.CURRENT_VERSION == ''
      shell: bash
      run: exit 1

    - name: Set output for new version
      id: set_output
      shell: bash
      run: |
        echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

    - name: Commit new version
      if: ${{ env.SKIP_BUMP == '0' }}
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -a -m "[ci skip] Bump version to ${NEW_VERSION}"

    - name: Get Commit Hash
      id: set_commit_hash
      shell: bash
      run: |
        COMMIT_HASH=$(git rev-parse HEAD)
        echo "Commit hash: $COMMIT_HASH"
        echo "commit_hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT

    - name: Build project for distribution
      shell: bash
      run: hatch build
