name: Cleanup WhiteSource Project

on:
  workflow_call:
    inputs:
      ws_product_name:
        type: string
        required: false
        default: "solaceai"
      ws_project_names:
        type: string
        required: false
        default: "${{ github.event.repository.name }}-pr-${{ github.event.number }},${{ github.event.repository.name }}-ui-pr-${{ github.event.number }}"
    secrets:
      ws_api_key:
        required: true

permissions:
  contents: read

jobs:
  cleanup-whitesource:
    name: Remove WhiteSource Project
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Whitesource is deptecated"
