name: Release to PyPi with Hatch

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "Environment to release to."
        type: string
        required: true
      version:
        description: "Version increment type."
        type: string
        required: true
      pypi-project:
        description: "PyPi repository to release to."
        type: string
        required: true
      npm_package_path:
        type: string
        required: false
        default: ""
        description: "Path to the npm package"
      node_version:
        type: string
        required: false
        default: "20"
        description: "Node version to use for the npm package"
      npm_lock_file:
        type: string
        required: false
        default: "package-lock.json"
        description: "Path to the npm lock file"

      whitesource_product_name:
        type: string
        required: false
        default: ""
        description: "Whitesource product name"
      whitesource_project_name:
        type: string
        required: false
        default: ""
        description: "Whitesource project name"
      prisma_check:
        type: boolean
        required: false
        default: false
        description: "Run Prisma check"
      sonarqube_hotspot_check:
        type: boolean
        required: false
        default: false
        description: "Run SonarQube Hotspot Check"
    secrets:
      COMMIT_KEY:
        description: "SSH private key for the repository."
        required: true
      PYPI_TOKEN:
        description: "PyPi token"
        required: true
      WHITESOURCE_API_KEY:
        description: "Whitesource API key"
        required: true
      MANIFEST_AWS_REGION:
        description: "AWS region for the manifest"
        required: false
      MANIFEST_AWS_ACCESS_KEY_ID:
        description: "AWS access key ID for the manifest"
        required: true
      MANIFEST_AWS_SECRET_ACCESS_KEY:
        description: "AWS secret access key for the manifest"
        required: true
      PRISMA_DOCKER_IMAGE_TO_CHECK:
        description: "Prisma docker image to check"
        required: false
      PRISMA_ACCESS_KEY:
        description: "Prisma access key ID"
        required: false
      PRISMA_ACCESS_KEY_SECRET:
        description: "Prisma secret access key"
        required: false

      SONARQUBE_PROJECT_KEY:
        description: "SonarQube project key"
        required: false
      SONARQUBE_PROJECT_MAIN_BRANCH:
        description: "SonarQube project main branch"
        required: false
      SONARQUBE_QUERY_TOKEN:
        description: "SonarQube query token"
        required: false
      SONARQUBE_HOTSPOTS_API_URL:
        description: "SonarQube hotspots API URL"
        required: false

permissions:
  id-token: write
  contents: write
  checks: write

jobs:
  release:
    name: release to PyPi
    timeout-minutes: 20
    environment: ${{ github.event.inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set_output.outputs.new_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - name: Run WhiteSource Policy Gate
        if: ${{ inputs.whitesource_product_name != '' && inputs.whitesource_project_name != '' }}
        uses: docker://ghcr.io/solacedev/maas-build-actions:ws-quiet
        env:
          WS_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
          WS_PRODUCT_NAME: ${{ inputs.whitesource_product_name }}
          WS_PROJECT_NAME: ${{ inputs.whitesource_project_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MANIFEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MANIFEST_AWS_SECRET_ACCESS_KEY }}
          WS_BLOCKING_POLICY_VIOLATION_LEVELS: "Major,Minor"
          FAIL_IF_POLICY_VIOLATIONS_FOUND: "True"
          STATUS_CHECK: "True"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ORG: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
          GH_SHA: ${{ github.sha }}
        with:
          entrypoint: /bin/sh
          args: >
            -c "
            . $VIRTUAL_ENV/bin/activate &&
            cd $ACTIONS_PATH/whitesource-policy-violation-checker &&
            python whitesource_policy_violation_checker.py
            "

      - name: Run WhiteSource Vulnerability Gate
        if: ${{ inputs.whitesource_product_name != '' && inputs.whitesource_project_name != '' }}
        uses: docker://ghcr.io/solacedev/maas-build-actions:ws-quiet
        env:
          WS_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
          WS_PRODUCT_NAME: ${{ inputs.whitesource_product_name }}
          WS_PROJECT_NAME: ${{ inputs.whitesource_project_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MANIFEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MANIFEST_AWS_SECRET_ACCESS_KEY }}
          WS_JIRA_CHECK: "True"
          JIRA_ONLY: "True"
          STATUS_CHECK: "True"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ORG: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
          GH_SHA: ${{ github.sha }}
        with:
          entrypoint: /bin/sh
          args: >
            -c ". $VIRTUAL_ENV/bin/activate &&
            cd $ACTIONS_PATH/whitesource-vulnerability-checker &&
            python whitesource_vulnerability_checker.py
            "

      - name: Run Prisma Check
        if: ${{ fromJson(inputs.prisma_check) }}
        uses: docker://ghcr.io/solacedev/maas-build-actions:ws-quiet
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MANIFEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MANIFEST_AWS_SECRET_ACCESS_KEY }}
          PRISMA_DOCKER_IMAGE_TO_CHECK: ${{ secrets.PRISMA_DOCKER_IMAGE_TO_CHECK }}
          PRISMA_ACCESS_KEY: ${{ secrets.PRISMA_ACCESS_KEY }}
          PRISMA_ACCESS_KEY_SECRET: ${{ secrets.PRISMA_ACCESS_KEY_SECRET }}
          PRISMA_JIRA_CHECK: "True"
          PRISMA_REPOSITORY_NAME: ${{ github.event.repository.name }}
          JIRA_ONLY: "True"
          STATUS_CHECK: "True"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ORG: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
          GH_SHA: ${{ github.sha }}
        with:
          entrypoint: /bin/sh
          args: >
            -c ". $VIRTUAL_ENV/bin/activate &&
            cd $ACTIONS_PATH/prisma-vulnerability-checker &&
            python prisma_vulnerability_checker.py
            "
      - name: Run SonarQube Hotspot Check
        uses: docker://ghcr.io/solacedev/maas-build-actions:ws-quiet
        if: ${{ fromJson(inputs.sonarqube_hotspot_check) }}
        env:
          SONARQUBE_PROJECT_KEY: ${{ secrets.SONARQUBE_PROJECT_KEY }}
          SONARQUBE_PROJECT_MAIN_BRANCH: ${{ secrets.SONARQUBE_PROJECT_MAIN_BRANCH }}
          SONARQUBE_QUERY_TOKEN: ${{ secrets.SONARQUBE_QUERY_TOKEN }}
          SONARQUBE_HOTSPOTS_API_URL: ${{ secrets.SONARQUBE_HOTSPOTS_API_URL }}
        with:
          entrypoint: /bin/sh
          args: >
            -c ". $VIRTUAL_ENV/bin/activate &&
            cd $ACTIONS_PATH/sonarqube-hotspot-checker &&
            python sonarqube_checker.py
            "

      - name: Setup Node.js
        if: inputs.npm_package_path != ''
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"
          cache-dependency-path: ${{ inputs.npm_package_path }}/${{ inputs.npm_lock_file }}

      - name: Install Dependencies
        if: inputs.npm_package_path != ''
        run: |
          cd ${{ inputs.npm_package_path }}
          npm install
          npm run build

      - name: Set up Hatch
        uses: SolaceDev/solace-public-workflows/.github/actions/hatch-setup@main
        with:
          build: "false"

      - name: Get Current Version
        id: current_version
        run: |
          CURRENT_VERSION=$(hatch version)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Check if last commit was a version bump commit
        id: check_bump
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit: $LAST_COMMIT_MSG"
          if echo "$LAST_COMMIT_MSG" | grep -q "\[ci skip\] Bump version to"; then
              echo "Previous commit was a version bump. Skipping version bump."
              echo "SKIP_BUMP=1" >> $GITHUB_ENV
          else
              echo "SKIP_BUMP=0" >> $GITHUB_ENV
          fi

      - name: Bump Version
        id: bump_version
        run: |
          if [ "$SKIP_BUMP" = "1" ]; then
              echo "Skipping version bump as the last commit was a version bump."
              echo "NEW_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
          else
              if [ -n "${{ github.event.inputs.full_version }}" ]; then
                  if [[ "${{ github.event.inputs.full_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                      hatch version "${{ github.event.inputs.full_version }}"
                  else
                      echo "Invalid full_version provided: ${{ github.event.inputs.full_version }}. Expected format x.y.z."
                      exit 1
                  fi
              else
                  hatch version "${{ github.event.inputs.version }}"
              fi
              NEW_VERSION=$(hatch version)
              echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          fi

      - name: Fail if the current version doesn't exist
        if: env.CURRENT_VERSION == ''
        run: exit 1

      - name: Set output for new version
        id: set_output
        run: |
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Commit new version
        if: ${{ env.SKIP_BUMP == '0' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "[ci skip] Bump version to ${NEW_VERSION}"
          git push

      - name: Build project for distribution
        run: hatch build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          verbose: true
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
        with:
          artifacts: "dist/*.whl"
          makeLatest: true
          generateReleaseNotes: true
          tag: ${{ env.NEW_VERSION }}
